import os
YOLO_MODEL_PATH = 'models/weapon_yolov8.pt'
CONF_BASE = 0.34
CONF_GENERIC_WEAPON = 0.45
CONF_ARMED_PERSON = 0.45
MIN_BOX_AREA_RATIO = 0.002
WEAPON_CLASSES = {'pistol', 'rifle', 'shotgun', 'knife', 'ax', 'weapon'}
ARMED_PERSON_CLASSES = {'person hold weapon'}
PERSON_CLASSES = {'person'}
LSTM_CHECKPOINT_PATH = 'C:\\Users\\milim\\Desktop\\real-time-crime-detection\\Threat\\checkpoints\\best_lstm.pth'
CLASSES = ['Normal', 'Anomaly']
NUM_CLASSES = len(CLASSES)
CLASS_TO_IDX = {c: i for i, c in enumerate(CLASSES)}
IDX_TO_CLASS = {i: c for c, i in CLASS_TO_IDX.items()}
NORMAL_CLASS = 'Normal'
NORMAL_IDX = CLASS_TO_IDX['Normal']
CLASS_SEVERITY = {'Normal': 'CLEAR', 'Anomaly': 'CRITICAL'}
CNN_BACKBONE = 'efficientnet_b0'
CNN_FEATURE_DIM = 512
IMG_SIZE = (224, 224)
BATCH_SIZE_CNN = 32
SEQ_LEN = 32
OVERLAP = 16
LSTM_HIDDEN = 128
LSTM_LAYERS = 1
DROPOUT = 0.5
FC_HIDDEN = 64
LSTM_ALERT_THRESHOLD = 0.54
CAMERA_LOCATION = {'name': 'Main Entrance — Block A', 'lat': 9.9312, 'lng': 76.2673, 'address': 'Muthoot Institute of Technology and Science, Kochi'}
CHECKPOINT_DIR = os.path.join('Threat', 'checkpoints')
BEST_MODEL_PATH = os.path.join(CHECKPOINT_DIR, 'best_lstm.pth')
LOG_DIR = os.path.join('Threat', 'logs')